/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Slots */
        get: operations["my_slots_me_slots_get"];
        put?: never;
        /** Create Slot */
        post: operations["create_slot_me_slots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/slots/{slot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Slot */
        delete: operations["delete_slot_me_slots__slot_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available Times */
        get: operations["available_times_slots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Reservation
         * @description 정식 로그인 고객 + QR 스코프 세션 모두 허용 — 단, 스코프 세션은
         *     검증을 통과한 그 결과지로만 예약 가능 (NFR-7 최소 권한).
         */
        post: operations["create_reservation_reservations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{reservation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Transition Reservation */
        patch: operations["transition_reservation_reservations__reservation_id__patch"];
        trace?: never;
    };
    "/me/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Reservations */
        get: operations["my_reservations_me_reservations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consult": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve Token
         * @description QR 스캔 직후: 토큰 서명 검증 → 검증 화면에 띄울 최소 정보.
         */
        get: operations["resolve_token_consult_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consult/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_consult_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-results/{test_result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Test Result
         * @description 접근 허용: 소유 고객 / 배정 상담사 / 이 결과지의 QR 스코프 세션.
         */
        get: operations["get_test_result_test_results__test_result_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-results/{test_result_id}/consult-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Consult Token
         * @description 결과지 상세 화면의 QR 이미지·딥링크용. 실물 인쇄분과 동일한 토큰 (§4.7 진입점 이원화).
         */
        get: operations["get_consult_token_test_results__test_result_id__consult_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Notifications */
        get: operations["my_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark Read */
        patch: operations["mark_read_notifications__notification_id__read_patch"];
        trace?: never;
    };
    "/records/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Draft
         * @description 메모 → 구조화 초안. 상담사가 검수·수정 후 저장하는 휴먼 인 더 루프 (§4.5).
         *
         *     LLM 장애 시에도 수기 작성 경로(/reservations/{id}/record)는 그대로 동작 (NFR-3).
         */
        post: operations["extract_draft_records_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{reservation_id}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Record */
        get: operations["get_record_reservations__reservation_id__record_get"];
        put?: never;
        /** Save Record */
        post: operations["save_record_reservations__reservation_id__record_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{reservation_id}/briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Briefing */
        get: operations["get_briefing_reservations__reservation_id__briefing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Purchase
         * @description 자사몰 주문 웹훅 (§4.5). 서명은 원문 바이트 기준 HMAC — 파싱 전에 검증한다.
         */
        post: operations["receive_purchase_webhooks_purchase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Subjects */
        get: operations["my_subjects_subjects_get"];
        put?: never;
        /** Create Subject */
        post: operations["create_subject_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/test-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subject Test Results */
        get: operations["subject_test_results_subjects__subject_id__test_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_admin_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AvailableTimesResponse */
        AvailableTimesResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Times */
            times: components["schemas"]["TimeAvailability"][];
            /** Alternatives */
            alternatives: components["schemas"]["DateAlternative"][];
        };
        /** BriefingResponse */
        BriefingResponse: {
            status: components["schemas"]["BriefingStatus"];
            /** Content */
            content: string | null;
        };
        /**
         * BriefingStatus
         * @enum {string}
         */
        BriefingStatus: "pending" | "processing" | "done" | "failed" | "cancelled";
        /**
         * ConsultInfoResponse
         * @description 검증 화면용 최소 정보. 이름은 마스킹 — 검증 전이므로 개인정보 비노출.
         */
        ConsultInfoResponse: {
            service_type: components["schemas"]["ServiceType"];
            /**
             * Reported At
             * Format: date
             */
            reported_at: string;
            /** Subject Name Masked */
            subject_name_masked: string;
        };
        /** ConsultTokenResponse */
        ConsultTokenResponse: {
            /** Token */
            token: string;
            /** Url */
            url: string;
        };
        /** ConsultVerifyRequest */
        ConsultVerifyRequest: {
            /** Token */
            token: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
        };
        /** DateAlternative */
        DateAlternative: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Available Count */
            available_count: number;
        };
        /**
         * DraftSource
         * @enum {string}
         */
        DraftSource: "manual" | "llm";
        /** ExtractRequest */
        ExtractRequest: {
            /** Raw Memo */
            raw_memo: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MetricsResponse
         * @description 관리자 지표 응답 (docs/04 §4.4). 비율은 분모 0(해당 기간 0건)이면 null —
         *     0%(실제 0건 처리)와 '계산 불가'를 구분한다.
         */
        MetricsResponse: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Total Reservations */
            total_reservations: number;
            /** Completed */
            completed: number;
            /** Cancelled */
            cancelled: number;
            /** No Show */
            no_show: number;
            /** Confirmed Upcoming */
            confirmed_upcoming: number;
            /** Completion Rate */
            completion_rate: number | null;
            /** No Show Rate */
            no_show_rate: number | null;
            /** Conversion Rate */
            conversion_rate: number | null;
            /** Top Interested Products */
            top_interested_products: components["schemas"]["ProductCount"][];
        };
        /** NotificationResponse */
        NotificationResponse: {
            /** Id */
            id: number;
            type: components["schemas"]["NotificationType"];
            /** Message */
            message: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Read */
            read: boolean;
        };
        /**
         * NotificationType
         * @enum {string}
         */
        NotificationType: "confirm" | "cancel" | "reminder_24h" | "reminder_1h" | "waitlist";
        /** ProductCount */
        ProductCount: {
            /** Product */
            product: string;
            /** Count */
            count: number;
        };
        /** PurchaseAck */
        PurchaseAck: {
            /** Order Id */
            order_id: string;
            /** Created */
            created: boolean;
            /** Matched */
            matched: boolean;
        };
        /**
         * RecordDraft
         * @description LLM 추출 결과의 스키마 검증 — 환각 필드·형식 오류를 여기서 한 번 더 차단.
         */
        RecordDraft: {
            /** Summary */
            summary: string;
            /** Interested Products */
            interested_products: string[];
            /** Recommendations */
            recommendations: string[];
            /** Follow Up */
            follow_up: string;
            /** Purchase Linked */
            purchase_linked: boolean;
        };
        /** RecordResponse */
        RecordResponse: {
            /** Id */
            id: number;
            /** Reservation Id */
            reservation_id: number;
            /** Raw Memo */
            raw_memo: string;
            /** Summary */
            summary: string | null;
            /** Interested Products */
            interested_products: string[];
            /** Recommendations */
            recommendations: string[];
            /** Follow Up */
            follow_up: string | null;
            /** Purchase Linked */
            purchase_linked: boolean;
            draft_source: components["schemas"]["DraftSource"];
        };
        /** RecordSaveRequest */
        RecordSaveRequest: {
            /** Raw Memo */
            raw_memo: string;
            /** Summary */
            summary?: string | null;
            /**
             * Interested Products
             * @default []
             */
            interested_products: string[];
            /**
             * Recommendations
             * @default []
             */
            recommendations: string[];
            /** Follow Up */
            follow_up?: string | null;
            /**
             * Purchase Linked
             * @default false
             */
            purchase_linked: boolean;
            /** @default manual */
            draft_source: components["schemas"]["DraftSource"];
        };
        /** ReservationCreate */
        ReservationCreate: {
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Subject Id */
            subject_id: number;
            /** Test Result Id */
            test_result_id: number;
            /** Pre Question */
            pre_question?: string | null;
        };
        /** ReservationResponse */
        ReservationResponse: {
            /** Id */
            id: number;
            status: components["schemas"]["ReservationStatus"];
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Subject Id */
            subject_id: number;
            /** Test Result Id */
            test_result_id: number;
            /** Counselor Name */
            counselor_name: string;
            /** Pre Question */
            pre_question: string | null;
        };
        /**
         * ReservationStatus
         * @enum {string}
         */
        ReservationStatus: "confirmed" | "completed" | "cancelled" | "no_show";
        /** ReservationTransitionRequest */
        ReservationTransitionRequest: {
            status: components["schemas"]["ReservationStatus"];
        };
        /** ScopedSessionResponse */
        ScopedSessionResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Test Result Id */
            test_result_id: number;
            /** Subject Id */
            subject_id: number;
            /** Expires In Minutes */
            expires_in_minutes: number;
        };
        /**
         * ServiceType
         * @description 분석 서비스 종류. 표시용 한글명은 프론트에서 매핑한다.
         * @enum {string}
         */
        ServiceType: "comprehensive_metabolic" | "food_intolerance" | "heavy_metal";
        /** SignupRequest */
        SignupRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
        };
        /** SlotCreate */
        SlotCreate: {
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
        };
        /** SlotResponse */
        SlotResponse: {
            /** Id */
            id: number;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /**
             * Has Active Reservation
             * @default false
             */
            has_active_reservation: boolean;
        };
        /** SubjectCreate */
        SubjectCreate: {
            /** Name */
            name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            relation: components["schemas"]["SubjectRelation"];
        };
        /**
         * SubjectRelation
         * @enum {string}
         */
        SubjectRelation: "self" | "family";
        /** SubjectResponse */
        SubjectResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            relation: components["schemas"]["SubjectRelation"];
        };
        /** TestResultResponse */
        TestResultResponse: {
            /** Id */
            id: number;
            /** Subject Id */
            subject_id: number;
            service_type: components["schemas"]["ServiceType"];
            /**
             * Reported At
             * Format: date
             */
            reported_at: string;
            /** Indicators */
            indicators: {
                [key: string]: unknown;
            }[];
        };
        /** TimeAvailability */
        TimeAvailability: {
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Available Count */
            available_count: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Name */
            name: string;
            /** Phone */
            phone: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "customer" | "counselor" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    my_slots_me_slots_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_slot_me_slots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_slot_me_slots__slot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    available_times_slots_get: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableTimesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reservation_reservations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_reservation_reservations__reservation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_reservations_me_reservations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"][];
                };
            };
        };
    };
    resolve_token_consult_get: {
        parameters: {
            query: {
                t: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_consult_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsultVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopedSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_test_result_test_results__test_result_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_result_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_consult_token_test_results__test_result_id__consult_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_result_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_notifications_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"][];
                };
            };
        };
    };
    mark_read_notifications__notification_id__read_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_draft_records_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_reservations__reservation_id__record_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_record_reservations__reservation_id__record_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_briefing_reservations__reservation_id__briefing_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_purchase_webhooks_purchase_post: {
        parameters: {
            query?: never;
            header?: {
                "x-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_subjects_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"][];
                };
            };
        };
    };
    create_subject_subjects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subject_test_results_subjects__subject_id__test_results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResultResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_admin_metrics_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
