"""예약 전이 시각 컬럼, 알림-예약 연결 FK

Revision ID: 29174be34eb4
Revises: cdc9aa5ef9cd
Create Date: 2026-07-09 14:09:42.402561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29174be34eb4'
down_revision: Union[str, Sequence[str], None] = 'cdc9aa5ef9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('reservation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'reservations', ['reservation_id'], ['id'])
    op.add_column('reservations', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reservations', sa.Column('no_show_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'no_show_at')
    op.drop_column('reservations', 'completed_at')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'reservation_id')
    # ### end Alembic commands ###
